local wk = require "which-key"

wk.add {
  { "<C-space>", "<Plug>(neorg.qol.todo-items.todo.task-cycle)", hidden = true },
  { "<CR>", "<Plug>(neorg.esupports.hop.hop-link)", hidden = true },
  { "<M-CR>", "<Plug>(neorg.esupports.hop.hop-link.vsplit)", hidden = true },
  { ";", group = "Norgmaps" },
  { ";l", group = "NorgLists" },
  { ";t", group = "NorgTodo" },
  { ";d", group = "NorgDemote" },
  { ";p", group = "NorgPromote" },
  { ";n", "<Plug>(neorg.dirman.new-note)", desc = "New note" },
  { ";da", "<Plug>(neorg.promo.demote)", desc = "Demote an object non-recursively" },
  { ";db", "<Plug>(neorg.promo.demote.nested)", desc = "Demote an object recursively" },
  { ";i", "<Plug>(neorg.tempus.insert-date)", desc = "Insert a link to a date at the given position" },
  { ";li", "<Plug>(neorg.pivot.list.invert)", desc = "List invert" },
  { ";lt", "<Plug>(neorg.pivot.list.toggle)", desc = "List toggle" },
  { ";ta", "<Plug>(neorg.qol.todo-items.todo.task-ambiguous)", desc = "Mark task as ambiguous" },
  { ";tc", "<Plug>(neorg.qol.todo-items.todo.task-cancelled)", desc = "Mark task as cancelled" },
  { ";td", "<Plug>(neorg.qol.todo-items.todo.task-done)", desc = "Mark task as done" },
  { ";th", "<Plug>(neorg.qol.todo-items.todo.task-on-hold)", desc = "Mark task as on hold" },
  { ";ti", "<Plug>(neorg.qol.todo-items.todo.task-important)", desc = "Mark task as important" },
  { ";tp", "<Plug>(neorg.qol.todo-items.todo.task-pending)", desc = "Mark task as pending" },
  { ";tr", "<Plug>(neorg.qol.todo-items.todo.task-recurring)", desc = "Mark task as recurring" },
  { ";tu", "<Plug>(neorg.qol.todo-items.todo.task-undone)", desc = "Mark task as undone" },
  { ";pa", "<Plug>(neorg.promo.promote)", desc = "Promote an object non-recursively" },
  { ";pb", "<Plug>(neorg.promo.promote.nested)", desc = "Promote an object recursively" },
  { ";d", "<Plug>(neorg.promo.demote.range)", desc = "Demote objects in range", mode = "v" },
  { ";p", "<Plug>(neorg.promo.promote.range)", desc = "Promote objects in range", mode = "v" },
  { "<C-d>", "<Plug>(neorg.promo.demote)", hidden = true, mode = "i" },
  { "<C-t>", "<Plug>(neorg.promo.promote)", hidden = true, mode = "i" },
  { "<M-CR>", "<Plug>(neorg.itero.next-iteration)", hidden = true, mode = "i" },
  { "<M-d>", "<Plug>(neorg.tempus.insert-date-insert-mode)", hidden = true, mode = "i" },
}
