require "xJAVIERx.launch"
require "xJAVIERx.options"
require "xJAVIERx.keymaps"
require "xJAVIERx.autocmds"
require "xJAVIERx.usercommands"
spec "xJAVIERx.catppuccin"
spec "xJAVIERx.xJAVTEXx"
spec "xJAVIERx.mini-icons"
spec "xJAVIERx.treesitter"
spec "xJAVIERx.mason"
spec "xJAVIERx.schemastore"
spec "xJAVIERx.lspconfig"
spec "xJAVIERx.cmp"
spec "xJAVIERx.lazydev"
spec "xJAVIERx.telescope"
spec "xJAVIERx.bibtelescope"
spec "xJAVIERx.trouble"
spec "xJAVIERx.gitsigns"
spec "xJAVIERx.none-ls"
spec "xJAVIERx.ltex_extra"
spec "xJAVIERx.typst"
spec "xJAVIERx.whichkey"
spec "xJAVIERx.neotree"
spec "xJAVIERx.comment"
spec "xJAVIERx.lualine"
spec "xJAVIERx.bufferline"
spec "xJAVIERx.neotab"
-- spec "xJAVIERx.navic"
-- spec "xJAVIERx.breadcrumbs"
spec "xJAVIERx.mini-pairs"
spec "xJAVIERx.neogit"
-- spec "xJAVIERx.fugitive"
spec "xJAVIERx.alpha"
spec "xJAVIERx.netrw"
spec "xJAVIERx.neorg"
spec "xJAVIERx.project"
spec "xJAVIERx.neoscroll"
spec "xJAVIERx.surround"
spec "xJAVIERx.todo-comments"
spec "xJAVIERx.colorizer"
spec "xJAVIERx.dressing"
spec "xJAVIERx.fidget"
-- spec "xJAVIERx.noice"
spec "xJAVIERx.bufdelete"
spec "xJAVIERx.pasteimage"
spec "xJAVIERx.peek"
spec "xJAVIERx.markmap"
-- spec "xJAVIERx.scnvim"
-- spec "xJAVIERx.tidalnvim"
spec "xJAVIERx.vim-socrates"
spec "xJAVIERx.undotree"
spec "xJAVIERx.scissors"
spec "xJAVIERx.render-markdown"
spec "xJAVIERx.just"
-- spec "xJAVIERx.screenkey"
-- spec "xJAVIERx.image"
require "xJAVIERx.lazy"
