#!/bin/sh

# Este script borra los archivos generados en la compilación de LaTeX/XeLaTeX.
# Un autocommand en Neovim llama este script al salir del documento TeX.

case "$1" in
	*.tex)
	file=$(readlink -f "$1")
	dir=$(dirname "$file")
	base="${file%.*}"
	find "$dir"  -maxdepth 1 -type f -regextype gnu-awk -regex "^$base\\.(4tc|xref|tmp|pyc|pyg|pyo|fls|vrb|fdb_latexmk|bak|swp|aux|log|synctex\\(busy\\)|lof|lot|maf|idx|mtc|mtc0|nav|out|snm|toc|bcf|run\\.xml|synctex\\.gz|blg|bbl)" -delete
	rm -rdf "$dir/_minted-$(basename -- "$base")"
	;;
	*) printf "Give .tex file as argument.\\n" ;;
esac
